########################################
# General Vars
########################################

variable "name" {
  default     = "mysql-rds"
  description = "common name for resources in this module"
  type        = string
}

variable "tags" {
  default     = {}
  description = "Tags to apply to supported resources"
  type        = map(string)
}

########################################
# Database Config Vars
########################################

variable "backup_retention_period" {
  default     = 0
  description = "How long to keep RDS backups (in days)"
  type        = number
}

variable "cloudwatch_log_exports" {
  description = "Log types to export to CloudWatch"
  type        = list(string)

  default = [
    "audit",
    "error",
    "general",
    "slowquery",
  ]
}

variable "copy_tags_to_snapshot" {
  default     = true
  description = "If `true`, RDS instance tags will be copied to snapshots"
  type        = bool
}

variable "enable_deletion_protection" {
  default     = true
  description = "If `true`, deletion protection will be turned on for the RDS instance(s)"
  type        = bool
}

variable "engine_version" {
  default     = null
  description = "Version of database engine to use"
  type        = string
}

variable "final_snapshot_identifier" {
  default     = null
  description = "name of final snapshot (will be computed automatically if not specified)"
  type        = string
}

variable "iam_database_authentication_enabled" {
  default     = false
  description = "Whether or not to enable IAM DB authentication"
  type        = bool
}

variable "parameters" {
  description = "Database parameters (will create parameter group if not null)"

  default = [
    {
      apply_method = "immediate"
      name         = "character_set_database"
      value        = "utf8"
    },
    {
      apply_method = "immediate"
      name         = "character_set_connection"
      value        = "utf8"
    },
    {
      apply_method = "immediate"
      name         = "character_set_filesystem"
      value        = "utf8"
    },
    {
      apply_method = "immediate"
      name         = "character_set_results"
      value        = "utf8"
    },
    {
      apply_method = "immediate"
      name         = "character_set_server"
      value        = "utf8"
    },
    {
      apply_method = "immediate"
      name         = "character_set_client"
      value        = "utf8"
    },
    {
      apply_method = "immediate"
      name         = "collation_connection"
      value        = "utf8_bin"
    },
    {
      apply_method = "immediate"
      name         = "collation_server"
      value        = "utf8_bin"
    },
    {
      apply_method = "immediate"
      name         = "max_allowed_packet"
      value        = "1073741824"
    },
    {
      apply_method = "immediate"
      name         = "read_only"
      value        = "1"
  }]

  type = list(object({
    apply_method = string
    name         = string
    value        = string
  }))
}
variable "performance_insights_enabled" {
  default     = false
  description = "If true, performance insights will be enabled"
  type        = bool
}

variable "skip_final_snapshot" {
  default     = false
  description = "If `true` no final snapshot will be taken on termination"
  type        = bool
}

########################################
# Instance Vars
########################################

variable "identifier_prefix" {
  default     = null
  description = "DB identifier prefix (will be generated by AWS automatically if not specified)"
  type        = string
}

variable "instance_class" {
  default     = "db.t3.small"
  description = "What instance type to use"
  type        = string
}

variable "monitoring_interval" {
  default     = 0
  description = "Monitoring interval in seconds (`0` to disable enhanced monitoring)"
  type        = number
}

variable "monitoring_role_arn" {
  default     = null
  description = "Enhanced Monitoring ARN (blank to omit)"
  type        = string
}

variable "multi_az" {
  default     = false
  description = "whether to make database multi-az"
  type        = bool
}

variable "storage_encrypted" {
  default     = true
  description = "Encrypt DB storage"
  type        = bool
}

variable "storage_type" {
  default     = "gp2"
  description = "What storage backend to use (`gp2` or `standard`. io1 not supported)"
  type        = string
}

########################################
# Networking Vars
########################################

variable "port" {
  description = "Port the database should listen on"
  type        = string
  default     = "3306"
}

########################################
# Read Replica Vars
########################################
variable "replicate_source_db_id" {
  description = "ID of RDS instance to replicate from"
  type        = string
  default     = null
}
